/* FUNCIÓN QUE RECIBE EL ID DE UN TIPO DE ENTIDAD 
   Y RETORNA EL NÚMERO DE ARTÍCULOS REGISTRADOS PARA
   EL GRUPO */

DELIMITER $$

CREATE FUNCTION numeroArticulos(
cod INT
)

RETURNS INT DETERMINISTIC
BEGIN
DECLARE cont INT DEFAULT 0;

SELECT COUNT(cod_entidad) INTO cont
FROM ARTICULOS
WHERE (cod_entidad = cod);

IF cont = 0 THEN
SET cont = NULL;
END IF;
RETURN cont;

END $$

DELIMITER ; 