/* FUNCIÓN QUE RECIBE EL ID DE UN TIPO DE ENTIDAD 
   Y RETORNA EL NÚMERO DE ARTÍCULOS REGISTRADOS PARA
   EL GRUPO */

DELIMITER $$

CREATE FUNCTION NumeroArticulos(
    id INT
) RETURNS INT NOT DETERMINISTIC
BEGIN    
    DECLARE cont INT DEFAULT 0;
    
    IF id NOT IN (SELECT cod_entidad FROM TIP0_ENTIDAD) THEN
        RETURN NULL;
    END IF;
        
    SELECT COUNT(cod_entidad) INTO cont 
    FROM ARTICULOS
    WHERE (id = cod_entidad);
    
    RETURN cont;
END $$

DELIMITER ;