DELIMITER //

CREATE PROCEDURE DUPLICAR_TIPO_ENTIDAD(IN cod INT)
BEGIN
    INSERT INTO TIPO_ENTIDAD(cod, descrip) 
    SELECT (SELECT MAX(cod_entidad) + 1), descrip FROM TIPO_ENTIDAD
    WHERE cod_entidad = cod;
END; //

DELIMITER ;