DELIMITER //

CREATE PROCEDURE DUPLICAR_TUPLA(IN cod INT)
BEGIN
    CREATE TEMPORARY TABLE TablaTemp SELECT * FROM TIPO_ENTIDAD WHERE cod_entidad = cod;
    UPDATE TablaTemp SET cod_entidad = NULL;
    INSERT INTO TIPO_ENTIDAD SELECT * FROM TablaTemp;
    DROP TEMPORARY TABLE IF EXISTS TablaTemp;
END; //

DELIMITER ;