DELIMITER //

CREATE TRIGGER VERIFIC_ULT_EVALUA BEFORE INSERT ON EVALUA
FOR EACH ROW 

BEGIN 
    IF ((SELECT DISTINCT cod_articulo FROM EVALUACIONES WHERE new.cod_articulo = cod_articulo)
         NOT IN (SELECT cod_articulo FROM ULTIMAS_EVALUACIONES)) THEN
        CALL OBT_ULTIMAS_EVALUACIONES();
    END IF;
END; //

DELIMITER ;

